### ISSUE TITLE
(503) Service Unavailable when using GitHub Sigstore instance

### ISSUE THREAD

**Issue by reidg44** [actions/attest#112]
When I run this action on a self-hosted runner for an image that will get pushed to a private registry, I get the following error:
`Error: InternalError: error creating signing certificate - (503) Service Unavailable`

Is the GitHub Sigstore instance unavailable? Or is something about my request causing the `503`?

**Comment by bdehamer** [comment]
@reidg44 I don't see any reports of errors on our side. Is your self-hosted runner behind a proxy?

**Comment by phillmv** [comment]
Closing this out for now. @reidg44 feel free to re-open if you're still having issues!
