### ISSUE TITLE
Timeout in OCI push

### ISSUE THREAD

**Issue by matthiasfehr** [actions/attest#91]
When using the action `actions/attest-build-provenance` with the option `push-to-registry` enabled, I regularly got a timeout error.

Digging into the action I discovered that the timeout corresponding to the OCI push is set [here](https://github.com/actions/attest/blob/main/src/attest.ts#L4) to 2 seconds, which is obviously pretty low and not every registry can fulfil the request in this time, especially not ones which are backed by an object storage.

May I ask here to increase the timeout to something more usual like e.g 30s?

For the time being, is there any possible workaround until this gets fixed?

**Comment by bdehamer** [comment]
@matthiasfehr I've got a fix queued up and will try to get this deployed today.

Out of curiosity, which OCI registry are you using?
